service: api-nest-alumnos
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  environment:
    API_KEY: ${env:API_KEY}
    DYNAMODB_TABLE: ${self:custom.tableName}
    CORS_ORIGIN: ${env:CORS_ORIGIN, ''}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: !GetAtt AlumnosTable.Arn
functions:
  createAlumno:
    handler: dist/main.handler
    events:
      - http:
          path: alumnos
          method: post
  getAlumnos:
    handler: dist/main.handler
    events:
      - http:
          path: alumnos
          method: get
  getAlumnoById:
    handler: dist/main.handler
    events:
      - http:
          path: alumnos/{id}
          method: get
  updateAlumno:
    handler: dist/main.handler
    events:
      - http:
          path: alumnos/{id}
          method: put
  deleteAlumno:
    handler: dist/main.handler
    events:
      - http:
          path: alumnos/{id}
          method: delete
plugins:
  - serverless-dynamodb-local
  - serverless-plugin-include-dependencies
  - serverless-auto-swagger
custom:
  tableName: ${env:DYNAMODB_TABLE, 'Alumnos'}
  autoswagger:
    title: 'api-nest-alumnos'
    apiType: 'http'
    apiKeyHeaders: ['api-key']
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
resources:
  Resources:
    AlumnosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
package:
  excludeDevDependencies: false
